apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
